spring:
  config:
    activate:
      on-profile: dev-profile
  datasource:
    url: jdbc:mysql://localhost:3306/deployment_study
    username: root
    password: minnnisu1560
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
serverName: dev-server