name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Docker build & push to docker repo
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -f app/Dockerfile -t ${{ secrets.DOCKER_REPO }}/deployment-study-spring-boot-app .
          docker push ${{ secrets.DOCKER_REPO }}/deployment-study-spring-boot-app
          cd nginx
          docker build -t ${{ secrets.DOCKER_REPO }}/deployment-study-nginx .
          docker push ${{ secrets.DOCKER_REPO }}/deployment-study-nginx
      - name: Upload docker-compose artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-compose-file
          path: ./docker-compose.yaml


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-compose-file
      - name: Transfer Docker-compose File use SCP
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.SHH_USER }}
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yaml"
          target: "~/deployment-study"
      - name: Execute App with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SHH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/deployment-study
            docker-compose down
            docker-compose up -d